# Generated by Django 3.2.5 on 2021-07-18 12:23

from django.db import migrations, models
import mail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSendler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(help_text='aaaaa@gmail.com;bbbb@gmail.com', max_length=400, null=True, validators=[mail.models.email_valid])),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('sending', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
